{
    'name': 'Custom Invoice & DO',
    'summary': 'Invoice & Delivery Order Custom Format',
    'version': '1.0',
    'category': 'Accounting',
    'author': 'Ronny Lim',
    'website': 'https://instagram.com/rjtcl_soft',
    'depends': ['account', 'stock'],
    'data': [
        'data/paperformat_data.xml',
        'report/report_invoice_mini.xml',
        'report/report_delivery_order.xml',
        'views/report_invoice_mini.xml',
        'views/invoice_form_button.xml',
        'views/delivery_order_form_button.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
